### ISSUE TITLE
autogen.sh errors on OSX re: PKG_PROG_PKG_CONFIG

### ISSUE THREAD

**Issue by revmischa** [sdroege/http-launch#4]
checking whether byte ordering is bigendian... no
./configure: line 13986: PKG_PROG_PKG_CONFIG: command not found
./configure: line 13988: syntax error near unexpected token `GST,'
./configure: line 13988: `PKG_CHECK_MODULES(GST, gstreamer-1.0 >= 1.0.8)'

**Comment by sdroege** [comment]
This should work if you have pkg-config installed. Do you?

**Comment by revmischa** [comment]
I do

**Comment by sdroege** [comment]
You should have /usr/share/aclocal/pkg.m4 then or in a similar directory, or your autoconf / pkg-config installation is broken

**Comment by revmischa** [comment]
I have /usr/local/share/aclocal/pkg.m4

**Comment by sdroege** [comment]
You'll have to check your autoconf installation then and why it doesn't find that file. Definitely a problem in your setup.
